---
title: 'Defence Against the Dark Arts using R and LaTeX Integrated via Quarto'
author: 'You R. Name'
degree: 'Master of Defence Against the Dark Arts'
university: 'University of Toronto'
department: 'Witchcraft and Wizardry'
year: 2022
abstract: "Defence Against the Dark Arts (in short, DADA) is about how to defend   
 against all aspects of the Dark Arts, including dark creatures, curses, hexes 
 and jinxes (dark charms), and duelling."
format:
  pdf:
    highlight: tango # "default", "tango", "pygments", "kate", "monochrome", "espresso", "zenburn", "haddock"
    template: "../tex/templatethesis.tex"
    top-level-division: chapter
    keep-tex: false
bibliography: ../bib/references.bib
csl: ../csl/chicago_manual_of_style_17th_edition_author_date.csl # Download your specific csl file and refer to it in the line below (see https://www.zotero.org/styles/)
amsmath: true
draft: true
---

<!--
This text in between arrows is commented and will be ignored in the final PDF.

Above is the YAML (YAML Ain't Markup Language) header that includes a lot of 
metadata used to produce the document.  Be careful with spacing in this header!

If you receive a duplicate label error after knitting, make sure to delete the 
index.Rmd file and then knit again.

You can delete all the lines starting with "#" in the header, also you can 
delete the bibliography and/or csl as well
-->

<!--
This chunk sets the global options and can be deleted, you could add
warning = FALSE or any other R Markdown option
-->
```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

# You can delete the next lines, but Knit without removing it first to 
# setup LaTeX. On Windows, you might need to restart your computer and try again 
# if knitting the document doesn't work.
if (!require("knitr")) install.packages("knitr", repos = "https://cran.rstudio.com")
if (!require("rmarkdown")) install.packages("rmarkdown", repos = "https://cran.rstudio.com")
if (!require("ggplot2")) install.packages("ggplot2", repos = "https://cran.rstudio.com")
if (!require("stargazer")) install.packages("stargazer", repos = "https://cran.rstudio.com")
if (!require("tinytex")) install.packages("tinytex", repos = "https://cran.rstudio.com")
if (isFALSE(tinytex::is_tinytex())) tinytex::install_tinytex()
```

<!--
The {#rmd-basics} text after the chapter declaration will allow us to link 
throughout the document back to the beginning of Chapter 1.  These labels will 
automatically be generated (if not specified) by changing the spaces to hyphens 
and capital letters to lowercase.  Look for the reference to this label at the 
beginning of Chapter 2.
-->

\mainmatter

```{r child = 'chapters/01-r-markdown-basics.rmd', eval = T}
```

```{r child = 'chapters/02-additional-resources.rmd', eval = T}
```

# References

---
nocite: | 
  @angel2000, @angel2001, @angel2002a
...
